### ISSUE TITLE
UnboundLocalError: local variable 'ID' referenced before assignment

### ISSUE THREAD

**Issue by mangood442** [MahmudX/SmallScrapingProjects#1]
from bs4 import BeautifulSoup
from time import sleep
import json

def Scrap(url, driver):
    na = "N/A"
    driver.get(url)
    sleep(1)

    # Get Overview
    soup = BeautifulSoup(driver.page_source, "html.parser")
    try:
        overview = soup.find_all('li', attrs={'class': 'jsx-1889249662'})
        over = []
        for x in overview:
            over.append(x.text)
        overview = ", ".join(over)
        if len(overview) == 0:
            overview = na
    except:
        overview = na

    try:
        driver.find_elements_by_class_name("react-tabs__tab")[1].click()
        soup = BeautifulSoup(driver.page_source, "html.parser")
    except:
        pass

    # Get Rating and reviews
    try:
       rating = soup.find(
           'p', attrs={"class": "jsx-2756475694 scoreTag"}).text
    except:
       rating = na

    try:
       reviews = soup.find(
           'p', attrs={"class": "jsx-2756475694 counter"}).text
    except:
       reviews = na

    #Get Breadcrumb
    try:
       breadcrumb = soup.find_all(
           'span', attrs={'class': 'jsx-447347517 crumb'})
       crumbs = []
       for x in breadcrumb:
           crumbs.append(x.text)
    except:
       crumbs = na
    breadcrumb = " > ".join(crumbs)

    # Get script
    scripts = soup.find_all(
        'script', attrs={'class': 'next-head', 'type': 'application/ld+json'})
    for x in scripts:
        try:
            sku = json.loads(x.text)
            ID = sku['sku']
            name = sku['name'].replace('Shop', '')
            desc = sku['description']
            brand = sku['brand']['name']
            producturl = sku['offers']["url"]
            images = sku['image']
            price = str(sku["offers"]['price']) + " " + \
                sku["offers"]['priceCurrency']
            break
        except:
            pass
    try:
        table = soup.find_all("tr", attrs={'class': "jsx-1537324451"})
        spec = []
        for x in table:
            s = x.find_all('td')
            spec.append((s[0].text + " : " + s[1].text))
        spec = ", ".join(spec)
    except:
        spec = na
    single = [ID, name, rating, reviews, desc, spec, overview,
              price, brand, breadcrumb, producturl]
    for x in images:
        single.append(x)
    return single

**Comment by MahmudX** [comment]
Can you give me the URL you are trying to scrap data from?

**Comment by mangood442** [comment]
https://www.noon.com/saudi-en/electronics-and-mobiles/mobiles-and-accessories/mobiles-20905
or any list from noon 
like this 
https://www.noon.com/saudi-en/p-12766

**Comment by MahmudX** [comment]
This file is designed to scrap data from the product page (e.g. [iPhone 11 Pro Max With FaceTime Midnight Green 256GB 4G LTE - KSA Specs](https://www.noon.com/saudi-en/iphone-11-pro-max-with-facetime-midnight-green-256gb-4g-lte-ksa-specs/N29885978A/p?o=ea78626ff141930c)), not the product listing page. Run the main.py and it should automatically collect list items from the listing page. Let me knows if anything happens.

**Comment by mangood442** [comment]
i know this script to scrap from page not list direct 
this is result after run default script

To scrap the entire website, type 'all' below.
Enter a valid url: all
Processing: https://www.noon.com/uae-en/galaxy-m31-dual-sim-blue-6gb-ram-128gb-4g-lte/N35521717A/p?o=d05a11d25e2d8e5d
Traceback (most recent call last):
  File "C:/Users/mango/Downloads/ProductScrap-master/ProductScrap-master/main.py", line 40, in <module>
    main()
  File "C:/Users/mango/Downloads/ProductScrap-master/ProductScrap-master/main.py", line 34, in main
    writer.writerow(prodscrapper.Scrap(x, driver))
  File "C:\Users\mango\Downloads\ProductScrap-master\ProductScrap-master\prodscrapper.py", line 79, in Scrap
    single = [ID, name, rating, reviews, desc, spec, overview,
UnboundLocalError: local variable 'ID' referenced before assignment

Process finished with exit code 1

**Comment by MahmudX** [comment]
hi! fixed some minor bugs. you can checkout. Directly scrap product data from main.py wasn't supported. here valid URL means listing page. I've add direct product page scrap support now. Checkout now.
